Update for L4T 36.3

diff --git a/CUDA/Dockerfile.jetson-agx-orin-devkit b/CUDA/Dockerfile.jetson-agx-orin-devkit
--- a/CUDA/Dockerfile.jetson-agx-orin-devkit
+++ b/CUDA/Dockerfile.jetson-agx-orin-devkit
@@ -1,43 +1,80 @@
-FROM balenalib/jetson-agx-orin-devkit-ubuntu:focal-run-20221215
+FROM balenalib/jetson-agx-orin-devkit-ubuntu:jammy-20240401
 
-# Don't prompt with any configuration questions
+# Prevent apt-get prompting for input
 ENV DEBIAN_FRONTEND noninteractive
 
-# Install some utils
-RUN apt-get update && apt-get install -y lbzip2 git wget unzip jq xorg tar \
-    python3 libegl1 binutils xz-utils zstd libglu1-mesa libglu1-mesa-dev \
-    freeglut3 freeglut3-dev
+RUN echo "deb https://repo.download.nvidia.com/jetson/common r36.3 main" >  /etc/apt/sources.list.d/nvidia.list \
+       && echo "deb https://repo.download.nvidia.com/jetson/t234 r36.3 main" >>  /etc/apt/sources.list.d/nvidia.list \
+       && apt-key adv --fetch-key http://repo.download.nvidia.com/jetson/jetson-ota-public.asc \
+       && mkdir -p /opt/nvidia/l4t-packages/ && touch /opt/nvidia/l4t-packages/.nv-l4t-disable-boot-fw-update-in-preinstall
 
-# Install CUDA
-RUN apt-get install -y nvidia-l4t-cuda nvidia-cuda cuda-samples-11-4
-
-# Set paths
-ENV CUDA_HOME=/usr/local/cuda-11.4
-
-# Build some (but not all) of the sample apps
+# Download and install BSP binaries for L4T 36.3 - Jetpack 6
 RUN \
-    export SMS=87 && \
-    cd /usr/local/cuda-11.4/samples/0_Simple/clock/ && make -j8 && \
-    cd /usr/local/cuda-11.4/samples/1_Utilities/deviceQuery/ && make -j8 && \
-    cd /usr/local/cuda-11.4/samples/2_Graphics/simpleTexture3D/ && make -j8 && \
-    cd /usr/local/cuda-11.4/samples/2_Graphics/simpleGL/ && make -j8 && \
-    cd /usr/local/cuda-11.4/samples/3_Imaging/postProcessGL/ && make -j8 && \
-    cd /usr/local/cuda-11.4/samples/5_Simulations/smokeParticles && make -j8
-
-ENV UDEV=1
-
-# Download and install BSP binaries for L4T 35.5.0
-RUN \
-    cd /tmp/ && wget https://developer.nvidia.com/embedded/l4t/r35_release_v5.0/release/jetson_linux_r35.5.0_aarch64.tbz2 && \
-    tar xf jetson_linux_r35.5.0_aarch64.tbz2 && \
+    apt-get update && apt-get install -y wget tar lbzip2 binutils xz-utils zstd qemu-user-static cpio git && cd /tmp/ && wget https://developer.nvidia.com/downloads/embedded/l4t/r36_release_v3.0/release/jetson_linux_r36.3.0_aarch64.tbz2 && \
+    tar xf jetson_linux_r36.3.0_aarch64.tbz2 && \
     cd Linux_for_Tegra && \
+    mkdir -p /tmp/Linux_for_Tegra/rootfs/boot/ && \
+    mkdir -p /tmp/Linux_for_Tegra/rootfs/usr/bin && \
+    mkdir -p /tmp/Linux_for_Tegra/rootfs/etc && touch /tmp/Linux_for_Tegra/rootfs/etc/resolv.conf && \
     sed -i 's/config.tbz2\"/config.tbz2\" --exclude=etc\/hosts --exclude=etc\/hostname/g' apply_binaries.sh && \
+    sed -i 's/CheckPackage qemu-user-static/#CheckPackage qemu-user-static/g' tools/l4t_update_initrd.sh && \
+    sed -i 's/trap CleanupVirEnv/#trap CleanupVirEnv/g' tools/l4t_update_initrd.sh&& \
+    sed -i 's|cp /usr/bin/qemu-aarch64-static|#cp /usr/bin/qemu-aarch64-static|g' tools/l4t_update_initrd.sh && \
+    sed -i 's|^UpdateInitrd|#UpdateInitrd|g' tools/l4t_update_initrd.sh && \
+    sed -i 's|^UpdateBackToBaseInitrd|#UpdateBackToBaseInitrd|g' tools/l4t_update_initrd.sh && \
+    sed -i 's|cp /etc/resolv.conf|#cp /etc/resolv.conf|g' tools/l4t_update_initrd.sh && \
+    sed -i 's|mv "${LDK_ROOTFS_DIR}/etc/resolv.conf"|cp "${LDK_ROOTFS_DIR}/etc/resolv.conf"|g' tools/l4t_update_initrd.sh && \
+    sed -i 's|  PrepareVirEnv|#PrepareVirEnv|g' tools/l4t_update_initrd.sh && \
     sed -i 's/install --owner=root --group=root \"${QEMU_BIN}\" \"${L4T_ROOTFS_DIR}\/usr\/bin\/\"/#install --owner=root --group=root \"${QEMU_BIN}\" \"${L4T_ROOTFS_DIR}\/usr\/bin\/\"/g' nv_tegra/nv-apply-debs.sh && \
     sed -i 's/chroot . \//  /g' nv_tegra/nv-apply-debs.sh && \
-    ./apply_binaries.sh -r / --target-overlay && cd .. \
+    cd /tmp/Linux_for_Tegra/ && ./apply_binaries.sh -r / --target-overlay && cd .. && \
     rm -rf Linux_for_Tegra && \
     echo "/usr/lib/aarch64-linux-gnu/tegra" > /etc/ld.so.conf.d/nvidia-tegra.conf && ldconfig
-    
-WORKDIR /usr/local/cuda-11.4/samples/bin/aarch64/linux/release
 
-CMD [ "sleep", "infinity" ]
+# Install X and xfce
+RUN apt-get install -y --no-install-recommends \
+   xserver-xorg-input-evdev \
+   xinit \
+   xfce4 \
+   xfce4-terminal \
+   x11-xserver-utils \
+   dbus-x11 \
+   xterm
+
+ENV LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra
+ENV UDEV=1
+
+# Prevent screen from turning off
+RUN echo "#!/bin/bash" > /etc/X11/xinit/xserverrc \
+   && echo "" >> /etc/X11/xinit/xserverrc \
+   && echo 'exec /usr/bin/X -s 0 dpms' >> /etc/X11/xinit/xserverrc && \
+   echo 'modules=("nvidia_drm"); for module in "${modules[@]}"; do if lsmod | grep -q ${module} ; then echo "Found $module"; rmmod $module; fi; done; startxfce4;' > /opt/startxfce.sh
+
+## If any apt packages install mesa-egl, it will overwrite the tegra-egl
+## symlink and ld path, so the following command will ensure tegra-egl remains
+## available:
+RUN \
+  echo "/usr/lib/aarch64-linux-gnu/tegra\n/usr/lib/aarch64-linux-gnu/tegra-egl" \
+  > /etc/ld.so.conf.d/000-nvidia-tegra-egl.conf \
+  && ldconfig
+
+## Install dependencies for some of the NVIDIA examples
+RUN \
+  apt-get install -y libegl1 binutils xz-utils zstd libglu1-mesa libglu1-mesa-dev \
+  freeglut3 freeglut3-dev
+    
+## Optional: Build some CUDA samples:
+RUN \
+   apt-get install -y -o Dpkg::Options::="--force-confdef" nvidia-l4t-cuda nvidia-cuda build-essential cuda-nvcc-12-2 && git clone https://github.com/NVIDIA/cuda-samples.git && cd cuda-samples/Samples/1_Utilities/deviceQuery && make # && ./deviceQuery
+
+
+RUN \
+    cd /cuda-samples/Samples/5_Domain_Specific/smokeParticles && make
+
+WORKDIR /usr/src/
+
+# Create a shell script for launching NVIDIA DRM
+RUN printf 'modules=("nvidia_drm"); for module in "${modules[@]}"; do if lsmod | grep -q ${module} ; then echo "Found $module"; rmmod $module; fi; done; sleep infinity;' > drm-script.sh && chmod +x drm-script.sh
+    
+
+CMD ["/bin/bash", "/usr/src/drm-script.sh"]
